name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install build-essential ; git clone https://github.com/jbruchon/libjodycode ../libjodycode ; pushd ../libjodycode ; make -j2 ; popd ; make -j2; pwd;; zip -j jdupes.zip ../libjodycode/libjodycode.so ../libjodycode/libjodycode.so.3 ../libjodycode/libjodycode.so.3.1

    - name: Upload Artifacts
      uses: actions/upload-artifact@main
      with:
            name: jdupes
            path: jdupes.zip
